name: evomap-package
channels:
  - defaults
dependencies:
  - python=3.9
  - ipykernel
  - numpy=1.24.3
  - numba=0.57.1
  - pandas=2.0.3
  - matplotlib=3.7.2
  - scipy=1.11.1
  - scikit-learn=1.3.0
  - statsmodels=0.14.0
  - seaborn=0.12.2
  - pip=24.0
  - jupyter=1.0.0
  - openpyxl=3.1.2
  - pip:
      - evomap==0.3.1
